module.exports.config = {
    name: 'autosend',
    version: '10.02',
    hasPermssion: 2,
    credits: 'Hwan',
    description: 'Tự động gửi tin nhắn theo giờ đã cài!',
    commandCategory: 'Hệ thống',
    usages: '[]',
    cooldowns: 3
  };
  const r = a => a[Math.floor(Math.random()*a.length)],
  {
    get
  } = require('axios'),
  config = [
          {
        timer: '6:30:00 AM',
    message: [' ====== [ 𝐓𝐡𝐨̂𝐧𝐠 𝐛𝐚́𝐨 ] ======\n◆━━━━━━━━━━━━━━━━◆\n[⏰] 𝐁𝐚̂𝐲 𝐠𝐢𝐨̛̀ 𝐥𝐚̀: {time} \n[💬] 𝐂𝐚̂𝐮 𝐭𝐡𝐢́𝐧𝐡:\n{thinh}💕\n◆━━━━━━━━━━━━━━━━◆ ']
  },
  {
        timer: '10:30:00 AM',
        message: [' ====== [ 𝐓𝐡𝐨̂𝐧𝐠 𝐛𝐚́𝐨 ] ======\n◆━━━━━━━━━━━━━━━━◆\n[⏰] 𝐁𝐚̂𝐲 𝐠𝐢𝐨̛̀ 𝐥𝐚̀: {time} \n[💬] 𝐂𝐚̂𝐮 𝐭𝐡𝐢́𝐧𝐡:\n{thinh}💕\n◆━━━━━━━━━━━━━━━━◆ ']
  },
  { 
        timer: '1:30:00 PM',
        message: [' ====== [ 𝐓𝐡𝐨̂𝐧𝐠 𝐛𝐚́𝐨 ] ======\n◆━━━━━━━━━━━━━━━━◆\n[⏰] 𝐁𝐚̂𝐲 𝐠𝐢𝐨̛̀ 𝐥𝐚̀: {time} \n[💬] 𝐂𝐚̂𝐮 𝐭𝐡𝐢́𝐧𝐡:\n{thinh}💕\n◆━━━━━━━━━━━━━━━━◆ ']
  },
        {
        timer: '4:30:00 PM',
        message: [' ====== [ 𝐓𝐡𝐨̂𝐧𝐠 𝐛𝐚́𝐨 ] ======\n◆━━━━━━━━━━━━━━━━◆\n[⏰] 𝐁𝐚̂𝐲 𝐠𝐢𝐨̛̀ 𝐥𝐚̀: {time} \n[💬] 𝐂𝐚̂𝐮 𝐭𝐡𝐢́𝐧𝐡:\n{thinh}💕\n◆━━━━━━━━━━━━━━━━◆ ']
    },
          {
        timer: '7:30:00 PM',
    message: [' ====== [ 𝐓𝐡𝐨̂𝐧𝐠 𝐛𝐚́𝐨 ] ======\n◆━━━━━━━━━━━━━━━━◆\n[⏰] 𝐁𝐚̂𝐲 𝐠𝐢𝐨̛̀ 𝐥𝐚̀: {time} \n[💬] 𝐂𝐚̂𝐮 𝐭𝐡𝐢́𝐧𝐡:\n{thinh}💕\n◆━━━━━━━━━━━━━━━━◆ ']
  },
  {
        timer: '9:30:00 PM',
        message: [' ====== [ 𝐓𝐡𝐨̂𝐧𝐠 𝐛𝐚́𝐨 ] ======\n◆━━━━━━━━━━━━━━━━◆\n[⏰] 𝐁𝐚̂𝐲 𝐠𝐢𝐨̛̀ 𝐥𝐚̀: {time} \n[💬] 𝐂𝐚̂𝐮 𝐭𝐡𝐢́𝐧𝐡:\n{thinh}💕\n◆━━━━━━━━━━━━━━━━◆ ']
  }
 
  ];

const axios = require('axios');
const fs = require('fs');
  // Danh sách các URL hình ảnh
  const imageUrls = [
    "https://i.imgur.com/uBVzoLu.jpg",
    "https://i.imgur.com/2SKrp2u.jpg",
    "https://i.imgur.com/eQScoB2.jpg",
    "https://i.imgur.com/sPTDj7J.jpg",
    "https://i.imgur.com/eKO5bbW.jpg",
    "https://i.imgur.com/OPoAuZz.jpg",
    "https://i.imgur.com/e8Hs2LK.jpg",
    "https://i.imgur.com/JB9Ma7r.jpg",
    "https://i.imgur.com/skZasjw.jpg",
    "https://i.imgur.com/uzlkEbQ.jpg",
    "https://i.imgur.com/BlCpMpt.jpg",
    "https://i.imgur.com/shE7rqH.jpg",
    "https://i.imgur.com/9pcXEs7.jpg",
    "https://i.imgur.com/lE0ryZt.jpg",
    "https://i.imgur.com/87tIKH3.jpg",
    "https://i.imgur.com/ISLIYWY.jpg",
    "https://i.imgur.com/MWzaNIp.jpg",
    "https://i.imgur.com/phQvE2O.jpg",
    "https://i.imgur.com/rWn34JA.jpg",
    "https://i.imgur.com/EazwRhR.jpg",
    "https://i.imgur.com/KDMhunJ.jpg",
    "https://i.imgur.com/08RUzA6.jpg",
    "https://i.imgur.com/kpFhb0p.jpg",
    "https://i.imgur.com/Ap5k1pG.jpg",
    "https://i.imgur.com/hPqyBrA.jpg",
    "https://i.imgur.com/giLgkEc.jpg",
    "https://i.imgur.com/zEUHhI8.jpg",
    "https://i.imgur.com/WJLKBbf.jpg",
    "https://i.imgur.com/7Whaezd.jpg",
    "https://i.imgur.com/8w3EYPR.jpg",
    "https://i.imgur.com/47dMIkP.jpg",
    "https://i.imgur.com/47dMIkP.jpg",
    "https://i.imgur.com/tDfrVtL.jpg",
    "https://i.imgur.com/gPKlKVv.jpg",
    "https://i.imgur.com/nLrLI5a.jpg",
    "https://i.imgur.com/n8tr6RJ.jpg",
    "https://i.imgur.com/jqDdNZy.jpg",
    "https://i.imgur.com/pC2aXuC.jpg",
    "https://i.imgur.com/YP28MO8.jpg",
    "https://i.imgur.com/KFwCJys.jpg",
    "https://i.imgur.com/KnRGveR.jpg",
    "https://i.imgur.com/ArLIBjf.jpg",
    "https://i.imgur.com/ZQSFJZP.jpg",
    "https://i.imgur.com/8j6zktC.jpg",
    "https://i.imgur.com/Lp1unUj.jpg",
    "https://i.imgur.com/4391tTY.jpg",
    "https://i.imgur.com/KoJVTEi.jpg",
    "https://i.imgur.com/uBVzoLu.jpg",
    "https://i.imgur.com/HZOBVcd.jpg",
    "https://i.imgur.com/MoozhQ4.jpg",
    "https://i.imgur.com/Vtx8zyF.jpg",
    "https://i.imgur.com/eLdLRuz.jpg",
    "https://i.imgur.com/D7SErWN.jpg",
    "https://i.imgur.com/JqkPa3w.jpg",
    "https://i.imgur.com/eg0oN3w.jpg",
    "https://i.imgur.com/Y92A06z.jpg",
    "https://i.imgur.com/t1nXKRE.jpg",
    "https://i.imgur.com/G4ZkJgb.jpg",
    "https://i.imgur.com/KDrZUTI.jpg",
    "https://i.imgur.com/BIGAkv6.jpg",
    "https://i.imgur.com/9evwBdF.jpg",
    "https://i.imgur.com/jzd9SOz.jpg",
    "https://i.imgur.com/ZP8Rt6X.jpg",
    "https://i.imgur.com/0mrUsLk.jpg",
    "https://i.imgur.com/CaaGAlS.jpg",
    "https://i.imgur.com/z30eQR7.jpg",
    "https://i.imgur.com/8cv9Qhb.jpg",
    "https://i.imgur.com/myWiaZq.jpg",
    "https://i.imgur.com/gpFOq8u.jpg",
    "https://i.imgur.com/8djscvM.jpg",
    "https://i.imgur.com/oQhh1At.jpg",
    "https://i.imgur.com/UUTCTH8.jpg",
    "https://i.imgur.com/IBfQmpC.jpg",
    "https://i.imgur.com/ZYBotms.jpg",
    "https://i.imgur.com/PKXpOLt.jpg",
    "https://i.imgur.com/A1A8yrW.jpg",
    "https://i.imgur.com/Fbmn8pJ.jpg",
    "https://i.imgur.com/zR59pVu.jpg",
    "https://i.imgur.com/COqwBC1.jpg",
    "https://i.imgur.com/7dmEDUP.jpg",
    "https://i.imgur.com/H3AvmJf.jpg",
    "https://i.imgur.com/fbjek1n.jpg",
    "https://i.imgur.com/EWIwuLd.jpg",
    "https://i.imgur.com/q5p2TVA.jpg",
    "https://i.imgur.com/r6xzEhh.jpg",
    "https://i.imgur.com/00HWAhf.jpg",
    "https://i.imgur.com/NMLh07O.jpg",
    "https://i.imgur.com/6jwc14e.jpg",
    "https://i.imgur.com/c42FSxG.jpg",
    "https://i.imgur.com/Bphtid4.jpg",
    "https://i.imgur.com/KHcANF2.jpg",
    "https://i.imgur.com/KjaAyqN.jpg",
    "https://i.imgur.com/P6ZeoXS.jpg",
    "https://i.imgur.com/j8W5TFs.jpg",
    "https://i.imgur.com/WoBjRsy.jpg",
    "https://i.imgur.com/X7Eqe5i.jpg",
    "https://i.imgur.com/329IoXX.jpg",
    "https://i.imgur.com/uEraREX.jpg",
    "https://i.imgur.com/XuLiXEn.jpg",
    "https://i.imgur.com/pK6Vnp7.jpg",
    "https://i.imgur.com/PePdM8G.jpg",
    "https://i.imgur.com/P6TpAy9.jpg",
    "https://i.imgur.com/LOqlDKp.jpg",
    "https://i.imgur.com/hrWNkBI.jpg",
    "https://i.imgur.com/dF0xt3s.jpg",
    "https://i.imgur.com/pZxDzpG.jpg",
    "https://i.imgur.com/xGTYbOn.jpg",
    "https://i.imgur.com/egb8dxR.jpg",
    "https://i.imgur.com/zvSZRzy.jpg",
    "https://i.imgur.com/Ryu6QWZ.jpg",
    "https://i.imgur.com/BRosV3A.jpg",
    "https://i.imgur.com/zWm8WwA.jpg",
    "https://i.imgur.com/c1jWpDB.jpg",
    "https://i.imgur.com/UE8usdY.jpg",
    "https://i.imgur.com/8Zj47pp.jpg",
    "https://i.imgur.com/8GshQuB.jpg",
    "https://i.imgur.com/8xDCDDp.jpg",
    "https://i.imgur.com/h34tnWu.jpg",
    "https://i.imgur.com/hJuhfT8.jpg",
    "https://i.imgur.com/bkFA67N.jpg",
    "https://i.imgur.com/vfhcOTr.jpg",
    "https://i.imgur.com/Cs4MkUV.jpg",
    "https://i.imgur.com/QN1SzhB.jpg",
    "https://i.imgur.com/JFdiZPE.jpg",
    "https://i.imgur.com/9iGBRwr.jpg",
    "https://i.imgur.com/tNImtzC.jpg",
    "https://i.imgur.com/6M3ykr2.jpg",
    "https://i.imgur.com/FO65fzi.jpg",
    "https://i.imgur.com/iTpcCCz.jpg",
    "https://i.imgur.com/BKC5g6y.jpg",
    "https://i.imgur.com/SiudRTz.jpg",
    "https://i.imgur.com/xFo96Mf.jpg",
    "https://i.imgur.com/3DZKX4f.jpg",
    "https://i.imgur.com/dMyrPeR.jpg",
    "https://i.imgur.com/ubNisAs.jpg",
    "https://i.imgur.com/Jao1lhp.jpg",
    "https://i.imgur.com/Jao1lhp.jpg",
    "https://i.imgur.com/9NHjJIr.jpg",
    "https://i.imgur.com/k6ZKhdx.jpg",
    "https://i.imgur.com/M6ukxPZ.jpg",
    "https://i.imgur.com/5OWq207.jpg",
    "https://i.imgur.com/gql5xEk.jpg",
    "https://i.imgur.com/g0XLrwK.jpg",
    "https://i.imgur.com/DAWuUMp.jpg",
    "https://i.imgur.com/8HCm0cO.jpg",
    "https://i.imgur.com/JPr6Vjv.jpg",
    "https://i.imgur.com/2x3NlSE.jpg",
    "https://i.imgur.com/2mQSGKi.jpg",
    "https://i.imgur.com/fvjdFHj.jpg",
    "https://i.imgur.com/ezlk5DM.jpg",
    "https://i.imgur.com/q7JUZ2Q.jpg",
    "https://i.imgur.com/MrzUC9p.jpg",
    "https://i.imgur.com/rBlFtcn.jpg",
    "https://i.imgur.com/NuBZ2ew.jpg",
    "https://i.imgur.com/bDXZ7K5.jpg",
    "https://i.imgur.com/RUKKFsZ.jpg",
    "https://i.imgur.com/dT5HoK9.jpg",
    "https://i.imgur.com/yrDSC9C.jpg",
    "https://i.imgur.com/ZeAifCC.jpg",
    "https://i.imgur.com/KIIWzuP.jpg",
    "https://i.imgur.com/I8HytB4.jpg",
    "https://i.imgur.com/wck3LCo.jpg",
    "https://i.imgur.com/yxP96pa.jpg",
    "https://i.imgur.com/AiQI8ji.jpg",
    "https://i.imgur.com/i1fQVol.jpg",
    "https://i.imgur.com/oaCkjvr.jpg",
    "https://i.imgur.com/cEroOxo.jpg",
    "https://i.imgur.com/Is044C1.jpg",
    "https://i.imgur.com/3ITbAwb.jpg",
    "https://i.imgur.com/0wizCbR.jpg",
    "https://i.imgur.com/D2TnwTK.jpg",
    "https://i.imgur.com/o6AF8DO.jpg",
    "https://i.imgur.com/eftfPpU.jpg", 
    "https://i.imgur.com/YNd3cfi.jpg",
    "https://i.imgur.com/nmvSmgA.jpg",
    "https://i.imgur.com/0mCTvKZ.jpg",
    "https://i.imgur.com/wrmnTLB.jpg",
    "https://i.imgur.com/DsliVjC.jpg",
    "https://i.imgur.com/4Uf7yOy.jpg",
    "https://i.imgur.com/fwM0YCo.jpg",
    "https://i.imgur.com/iPSvMsA.jpg",
    "https://i.imgur.com/82feFJN.jpg",
    "https://i.imgur.com/kgFkxpt.jpg",
    "https://i.imgur.com/ovavB03.jpg",
    "https://i.imgur.com/NPWrdte.jpg",
    "https://i.imgur.com/KAuo1xc.jpg",
    "https://i.imgur.com/dG6mP5k.jpg",
    "https://i.imgur.com/UE2x39t.jpg",
    "https://i.imgur.com/sf6bGUi.jpg",
    "https://i.imgur.com/Ced2wWS.jpg",
    "https://i.imgur.com/t3LRpAd.jpg",
    "https://i.imgur.com/IJWR5tr.jpg",
    "https://i.imgur.com/NQvTGX7.jpg",
    "https://i.imgur.com/eaQKd9i.jpg",
    "https://i.imgur.com/GgUvWXG.jpg",
    "https://i.imgur.com/d8yfkjL.jpg",
    "https://i.imgur.com/w8jNdWT.jpg",
    "https://i.imgur.com/fhrnMHt.jpg",
    "https://i.imgur.com/CqHx5G3.jpg",
    "https://i.imgur.com/nSdyduB.jpg",
    "https://i.imgur.com/TavhaCC.jpg",
    "https://i.imgur.com/JSozXDn.jpg",
    "https://i.imgur.com/PycHFqC.jpg",
    "https://i.imgur.com/lywnLQh.jpg",
    "https://i.imgur.com/ResijOM.jpg",
    "https://i.imgur.com/2QZHfKi.jpg",
    "https://i.imgur.com/3b8HVDz.jpg",
    "https://i.imgur.com/K8Vf1to.jpg",
    "https://i.imgur.com/SFXLEQM.jpg",
    "https://i.imgur.com/lIpZNy7.jpg",
    "https://i.imgur.com/HRx6vj2.jpg",
    "https://i.imgur.com/NKU66Da.jpg",
    "https://i.imgur.com/nmCcY9i.jpg",
    "https://i.imgur.com/2ZZrpkq.jpg",
    "https://i.imgur.com/wTSnzSX.jpg",
    "https://i.imgur.com/oJUUfBX.jpg",
    "https://i.imgur.com/WoCsmAX.jpg",
    "https://i.imgur.com/cHH6rTl.jpg",
    "https://i.imgur.com/haopYQL.jpg",
    "https://i.imgur.com/xqymKfp.jpg",
    "https://i.imgur.com/InNKEZm.jpg",
    "https://i.imgur.com/l3gmjF9.jpg",
    "https://i.imgur.com/Zd1dzsJ.jpg",
    "https://i.imgur.com/sh8zM3d.jpg",
    "https://i.imgur.com/z21900b.jpg",
    "https://i.imgur.com/A41JHAf.jpg",
    "https://i.imgur.com/u1ZMB24.jpg",
    "https://i.imgur.com/ljXoGVD.jpg",
    "https://i.imgur.com/bH2gLBG.jpg",
    "https://i.imgur.com/bH2gLBG.jpg",
    "https://i.imgur.com/yzbZi9Z.jpg",
    "https://i.imgur.com/VL9DQxu.jpg",
    "https://i.imgur.com/VrIXG57.jpg",
    "https://i.imgur.com/eBfPxQk.jpg",
    "https://i.imgur.com/nMMmjHH.jpg",
    "https://i.imgur.com/QFtwH3u.jpg",
    "https://i.imgur.com/7YMf4mV.jpg",
    "https://i.imgur.com/IViRBcE.jpg",
    "https://i.imgur.com/NKjA7Kq.jpg",
    "https://i.imgur.com/fFinnH5.jpg",
    "https://i.imgur.com/MgDGqwI.jpg",
    "https://i.imgur.com/UY2vZLH.jpg",
    "https://i.imgur.com/kU9X5uc.jpg",
    "https://i.imgur.com/dM3He80.jpg",
    "https://i.imgur.com/4XpKFsN.jpg",
    "https://i.imgur.com/wb9M9JC.jpg",
    "https://i.imgur.com/IzejH85.jpg",
    "https://i.imgur.com/s1Mi1wX.jpg",
    "https://i.imgur.com/XjlRI28.jpg",
    "https://i.imgur.com/wzvAdVR.jpg",
    "https://i.imgur.com/C7hE9FP.jpg",
    "https://i.imgur.com/4aO4q18.jpg",
    "https://i.imgur.com/MMYYUOv.jpg",
    "https://i.imgur.com/BWrW0pc.jpg",
    "https://i.imgur.com/llUTK6s.jpg",
    "https://i.imgur.com/TkSwDzk.jpg",
    "https://i.imgur.com/gJUiO3H.jpg",
    "https://i.imgur.com/QmeOeAm.jpg",
    "https://i.imgur.com/mDas8Gz.jpg",
    "https://i.imgur.com/lNLJcup.jpg",
    "https://i.imgur.com/FgT5IvE.jpg",
    "https://i.imgur.com/5TklKC9.jpg",
    "https://i.imgur.com/YxOmJcR.jpg",
    "https://i.imgur.com/SVnb6eI.jpg",
    "https://i.imgur.com/jXjhqP5.jpg",
    "https://i.imgur.com/ye4089A.jpg",
    "https://i.imgur.com/bFHgHSk.jpg",
    "https://i.imgur.com/qIA6pQ8.jpg",
    "https://i.imgur.com/AtyhKAq.jpg",
    "https://i.imgur.com/kAFVmJq.jpg",
    "https://i.imgur.com/8d13Ew1.jpg",
    "https://i.imgur.com/8yMH2yv.jpg",
    "https://i.imgur.com/Ic2056B.jpg",
    "https://i.imgur.com/QYm4giw.jpg",
    "https://i.imgur.com/DQbIvgr.jpg",
    "https://i.imgur.com/30BadYZ.jpg",
    "https://i.imgur.com/iUQ7u4Q.jpg",
    "https://i.imgur.com/miqFvNQ.jpg",
    "https://i.imgur.com/uiVYT2F.jpg",
    "https://i.imgur.com/XCqBEkN.jpg",
    "https://i.imgur.com/xAlKJQ2.jpg",
    "https://i.imgur.com/mfGbZha.jpg",
    "https://i.imgur.com/GByCvD6.jpg",
    "https://i.imgur.com/a21zP6N.jpg",
    "https://i.imgur.com/I1AaHp5.jpg",
    "https://i.imgur.com/FnVESWd.jpg",
    "https://i.imgur.com/WBOUW25.jpg",
    "https://i.imgur.com/nfNnmqx.jpg",
    "https://i.imgur.com/ebCadqH.jpg",
    "https://i.imgur.com/Jo174bO.jpg",
    "https://i.imgur.com/IG0Rnzj.jpg",
    "https://i.imgur.com/UzFMv3J.jpg",
    "https://i.imgur.com/kVZj3ek.jpg",
    "https://i.imgur.com/eo59vej.jpg",
    "https://i.imgur.com/miIq4tM.jpg",
    "https://i.imgur.com/jcYGame.jpg",
    "https://i.imgur.com/dV2MYZ7.jpg",
    "https://i.imgur.com/o2bOKWI.jpg",
    "https://i.imgur.com/UCXdOvJ.jpg",
    "https://i.imgur.com/uT8xFxk.jpg",
    "https://i.imgur.com/0qsJQFC.jpg",
    "https://i.imgur.com/bPPqf8q.jpg",
    "https://i.imgur.com/MU3b3Ft.jpg",
    "https://i.imgur.com/j20apMZ.jpg",
    "https://i.imgur.com/IMklyPW.jpg",
    "https://i.imgur.com/2UdyG23.jpg",
    "https://i.imgur.com/to5rFwL.jpg",
    "https://i.imgur.com/76TPN0r.jpg",
    "https://i.imgur.com/h46o5Jv.jpg",
    "https://i.imgur.com/3fLi4gr.jpg",
    "https://i.imgur.com/JK8dQsM.jpg",
    "https://i.imgur.com/N2rGKcT.jpg",
    "https://i.imgur.com/4rhnIqe.jpg",
    "https://i.imgur.com/ZftkNyK.jpg",
    "https://i.imgur.com/7t9LKeU.jpg",
    "https://i.imgur.com/XaBilR7.jpg",
    "https://i.imgur.com/QMlZUL5.jpg",
    "https://i.imgur.com/BbTdVv5.jpg",
    "https://i.imgur.com/nWmf9tS.jpg",
    "https://i.imgur.com/z4Wnntx.jpg",
    "https://i.imgur.com/YOUP1g0.jpg",
    "https://i.imgur.com/36wGuiS.jpg",
    "https://i.imgur.com/Q70qqcJ.jpg",
    "https://i.imgur.com/VA36xMR.jpg",
    "https://i.imgur.com/db5H8di.jpg",
    "https://i.imgur.com/MCrcqq8.jpg",
    "https://i.imgur.com/k3ibI7N.jpg",
    "https://i.imgur.com/DDYtTi4.jpg",
    "https://i.imgur.com/5GZroxJ.jpg",
    "https://i.imgur.com/08Epfdy.jpg",
    "https://i.imgur.com/XmBpeNz.jpg",
    "https://i.imgur.com/n7PKvpx.jpg",
    "https://i.imgur.com/GqrC1m4.jpg",
    "https://i.imgur.com/53ZKUQf.jpg",
    "https://i.imgur.com/nhPEejZ.jpg",
    "https://i.imgur.com/iR53VGf.jpg",
    "https://i.imgur.com/WT8KzCP.jpg",
    "https://i.imgur.com/AKp02J2.jpg",
    "https://i.imgur.com/mHBSv9Q.jpg",
    "https://i.imgur.com/GkigeJp.jpg",
    "https://i.imgur.com/4T2ZfiS.jpg",
    "https://i.imgur.com/gPA9Ryr.jpg",
    "https://i.imgur.com/hf7iiZz.jpg",
    "https://i.imgur.com/JyrgbJU.jpg",
    "https://i.imgur.com/rprQJ1V.jpg",
    "https://i.imgur.com/Pcx8bpX.jpg",
    "https://i.imgur.com/gPF2Ibv.jpg",
    "https://i.imgur.com/YKkqPw7.jpg",
    "https://i.imgur.com/1AdwMb8.jpg",
    "https://i.imgur.com/B1JFlfx.jpg",
    "https://i.imgur.com/d8KcUDx.jpg",
    "https://i.imgur.com/lmiN0il.jpg",
    "https://i.imgur.com/TENHIcB.jpg",
    "https://i.imgur.com/D6QP53P.jpg",
    "https://i.imgur.com/OyzoOo8.jpg",
    "https://i.imgur.com/JLCobwK.jpg",
    "https://i.imgur.com/jptflKY.jpg",
    "https://i.imgur.com/UfmYGZ5.jpg",
    "https://i.imgur.com/QhgNXa0.jpg",
    "https://i.imgur.com/DatPZV3.jpg",
    "https://i.imgur.com/wMBKaI9.jpg",
    "https://i.imgur.com/T4OhKRh.jpg",
    "https://i.imgur.com/EyTAj0e.jpg",
    "https://i.imgur.com/5FK3zMv.jpg",
    "https://i.imgur.com/4Ycs3wr.jpg",
    "https://i.imgur.com/84J7TsV.jpg",
    "https://i.imgur.com/kdKiL60.jpg",
    "https://i.imgur.com/N2rGKcT.jpg",
    "https://i.imgur.com/z4Wnntx.jpg",
    "https://i.imgur.com/BuSK9wj.jpg",
    "https://i.imgur.com/mxzGM6L.jpg",
    "https://i.imgur.com/pzMsumF.jpg",
    "https://i.imgur.com/PABqjZw.jpg",
    "https://i.imgur.com/MAKlMsv.jpg",
    "https://i.imgur.com/EFJQyag.jpg",
    "https://i.imgur.com/1ibPvKm.jpg",
    "https://i.imgur.com/sfV6JjU.jpg",
    "https://i.imgur.com/YaIDrcd.jpg",
    "https://i.imgur.com/uOlJGvD.jpg",
    "https://i.imgur.com/bvwOFVx.jpg",
    "https://i.imgur.com/XRhF1R7.jpg",
    "https://i.imgur.com/fQ43pBN.jpg",
    "https://i.imgur.com/6Q13MMp.jpg",
    "https://i.imgur.com/laXjssM.jpg",
    "https://i.imgur.com/LcaAnuV.jpg",
    "https://i.imgur.com/sOAzq5C.jpg",
    "https://i.imgur.com/hPJF4dt.jpg",
    "https://i.imgur.com/GoZjsGx.jpg",
    "https://i.imgur.com/QCjcaDp.jpg",
    "https://i.imgur.com/ZaSSxZi.jpg",
    "https://i.imgur.com/4fLaOi1.jpg",
    "https://i.imgur.com/5HH42Ro.jpg",
    "https://i.imgur.com/zwU5qUL.jpg",
    "https://i.imgur.com/tXrXjx2.jpg",
    "https://i.imgur.com/1LEuiJz.jpg",
    "https://i.imgur.com/VlvHChV.jpg",
    "https://i.imgur.com/dmpGCN1.jpg",
    "https://i.imgur.com/YE3WdOY.jpg",
    "https://i.imgur.com/VisbgaM.jpg",
    "https://i.imgur.com/1tjWaKD.jpg",
    "https://i.imgur.com/FikZlck.jpg",
    "https://i.imgur.com/DHdGYj4.jpg",
    "https://i.imgur.com/XtnT0pH.jpg",
    "https://i.imgur.com/quRbpkr.jpg",
    "https://i.imgur.com/rAnKeyf.jpg",
    "https://i.imgur.com/LZlken9.jpg",
    "https://i.imgur.com/SWvysgF.jpg",
    "https://i.imgur.com/lJAc1zp.jpg",
    "https://i.imgur.com/5zOMqzS.jpg",
    "https://i.imgur.com/QbY8QVJ.jpg",
    "https://i.imgur.com/q2Ldwme.jpg",
    "https://i.imgur.com/RZUMiW5.jpg",
    "https://i.imgur.com/SUYesdu.jpg",
    "https://i.imgur.com/QrdAQ5O.jpg",
    "https://i.imgur.com/i3REQPl.jpg",
    "https://i.imgur.com/QTDv8VR.jpg",
    "https://i.imgur.com/YGYz8Zf.jpg",
    "https://i.imgur.com/lVdQpXU.jpg",
    "https://i.imgur.com/UQyTtb2.jpg",
    "https://i.imgur.com/wn0WkL5.jpg",
    "https://i.imgur.com/dnqx5rh.jpg",
    "https://i.imgur.com/RItVqNC.jpg",
    "https://i.imgur.com/hLu73rU.jpg",
    "https://i.imgur.com/9PtXc8P.jpg",
    "https://i.imgur.com/OQlvbaI.jpg",
    "https://i.imgur.com/QhtPHyV.jpg",
    "https://i.imgur.com/xGrKrCL.jpg",
    "https://i.imgur.com/Xbc4czE.jpg",
    "https://i.imgur.com/bPbHMgF.jpg",
    "https://i.imgur.com/ebaQwrJ.jpg",
    "https://i.imgur.com/bZcBCUN.jpg",
    "https://i.imgur.com/rc8TFsH.jpg",
    "https://i.imgur.com/XAVTyMv.jpg",
    "https://i.imgur.com/bPbHMgF.jpg",
    "https://i.imgur.com/ebaQwrJ.jpg",
    "https://i.imgur.com/bZcBCUN.jpg",
    "https://i.imgur.com/rc8TFsH.jpg",
    "https://i.imgur.com/XAVTyMv.jpg",
    "https://i.imgur.com/8b1Ocv0.jpg",
    "https://i.imgur.com/wfypdLF.jpg",
    "https://i.imgur.com/ebaQwrJ.jpg",
    "https://i.imgur.com/TAtk5Y6m.jpg",
    "https://i.imgur.com/UW5d9hUm.jpg",
    "https://i.imgur.com/xVh8bMBm.jpg",
    "https://i.imgur.com/WNKW4Crm.jpg",
    "https://i.imgur.com/RQEE7MOm.jpg",
    "https://i.imgur.com/Jatu9LP.jpg",
    "https://i.imgur.com/ldu58vm.jpg",
    "https://i.imgur.com/Hg9KIxb.jpg",
    "https://i.imgur.com/iRzlqeW.jpg",
    "https://i.imgur.com/z5dPmrJ.jpg",
    "https://i.imgur.com/mpQV8GT.jpg",
    "https://i.imgur.com/VFt1K0V.jpg",
    "https://i.imgur.com/8OKwJW1.jpg",
    "https://i.imgur.com/ZIP1FP4.jpg",
    "https://i.imgur.com/dxvZH37.jpg",
    "https://i.imgur.com/RFDZKFj.jpg",
    "https://i.imgur.com/XFFouGc.jpg",
    "https://i.imgur.com/2f0dw4K.jpg",
    "https://i.imgur.com/nn727PG.jpg",
    "https://i.imgur.com/TBCimSX.jpg",
    "https://i.imgur.com/oCcg5Fw.jpg",
    "https://i.imgur.com/5mh8wSO.jpg",
    "https://i.imgur.com/qk9PNdy.jpg",
    "https://i.imgur.com/W4FCiND.jpg",
    "https://i.imgur.com/bKs7uzK.jpg",
    "https://i.imgur.com/yKvB0VX.jpg",
    "https://i.imgur.com/MPfQUVA.jpg",
    "https://i.imgur.com/21CCbKg.jpg",
    "https://i.imgur.com/o9wFEBS.jpg",
    "https://i.imgur.com/Yb7XvSi.jpg",
    "https://i.imgur.com/YvZk4YP.jpg",
    "https://i.imgur.com/MDB3Bso.jpg",
    "https://i.imgur.com/YHEgptk.jpg",
    "https://i.imgur.com/nZJVxmo.jpg",
    "https://i.imgur.com/MvoGz17.jpg",
    "https://i.imgur.com/d1XBWEK.jpg",
    "https://i.imgur.com/RPJlqeN.jpg",
    "https://i.imgur.com/j0ibNav.jpg",
    "https://i.imgur.com/wcNDVtK.jpg",
    "https://i.imgur.com/JElUKxD.jpg",
    "https://i.imgur.com/nlCaEMM.jpg",
    "https://i.imgur.com/1YY7YWT.jpg",
    "https://i.imgur.com/1Th2qr2.jpg",
    "https://i.imgur.com/jVUiPYW.jpg",
    "https://i.imgur.com/OLRb8OI.jpg",
    "https://i.imgur.com/Xmw89Jm.jpg",
    "https://i.imgur.com/FGHtfhh.jpg",
    "https://i.imgur.com/my52wRp.jpg",
    "https://i.imgur.com/8H4Cz9G.jpg",
    "https://i.imgur.com/gMzNy08.jpg",
    "https://i.imgur.com/6cmuBaJ.jpg",
    "https://i.imgur.com/uSMIqkW.jpg",
    "https://i.imgur.com/9pUrjPe.jpg",
    "https://i.imgur.com/ZrbGDoQ.jpg",
    "https://i.imgur.com/jXtwfM4.jpg",
    "https://i.imgur.com/s5W7tiK.jpg",
    "https://i.imgur.com/EZt5UaQ.jpg",
    "https://i.imgur.com/QShXMew.jpg",
    "https://i.imgur.com/nPngf6v.jpg",
    "https://i.imgur.com/kdaDb4X.jpg",
    "https://i.imgur.com/FUJGorV.jpg",
    "https://i.imgur.com/cwG3y3k.jpg",
    "https://i.imgur.com/3gR9xWA.jpg",
    "https://i.imgur.com/qIGblSW.jpg",
    "https://i.imgur.com/sZFVfTi.jpg",
    "https://i.imgur.com/fRKtCh2.jpg",
    "https://i.imgur.com/72t57mO.jpg",
    "https://i.imgur.com/ddSIHmf.jpg",
    "https://i.imgur.com/0MyPb0A.jpg",
    "https://i.imgur.com/AOO7tf8.jpg",
    "https://i.imgur.com/MOr38ja.jpg",
    "https://i.imgur.com/jntXadj.jpg",
    "https://i.imgur.com/dyLOwwx.jpg",
    "https://i.imgur.com/nAWsh01.jpg",
    "https://i.imgur.com/4opfulr.jpg",
    "https://i.imgur.com/Jtq2Dp7.jpg",
    "https://i.imgur.com/7kc5ZQN.jpg",
    "https://i.imgur.com/DnwYkqV.jpg",
    "https://i.imgur.com/CG8jObY.jpg",
    "https://i.imgur.com/dt3XB0d.jpg",
    "https://i.imgur.com/eSldU56.jpg",
    "https://i.imgur.com/8WNHKPZ.jpg",
    "https://i.imgur.com/AOezFPl.jpg",
    "https://i.imgur.com/s8H8vXo.jpg",
    "https://i.imgur.com/hNsPnN3.jpg",
    "https://i.imgur.com/vLfugFC.jpg",
    "https://i.imgur.com/0oVLKgi.jpg",
    "https://i.imgur.com/suQnclj.jpg",
    "https://i.imgur.com/AUtyy6b.jpg",
    "https://i.imgur.com/lDWTXhL.jpg",
    "https://i.imgur.com/cepagrm.jpg",
    "https://i.imgur.com/Moisx3w.jpg",
    "https://i.imgur.com/g8ZmzWp.jpg",
    "https://i.imgur.com/vs2xbHe.jpg",
    "https://i.imgur.com/cqD8QvL.jpg",
    "https://i.imgur.com/D4lsL8Y.jpg",
    "https://i.imgur.com/DWPcQ2C.jpg",
    "https://i.imgur.com/XADHLRO.jpg",
    "https://i.imgur.com/KQnLYLN.jpg",
    "https://i.imgur.com/hzqil4z.jpg",
    "https://i.imgur.com/KXm0avO.jpg",
    "https://i.imgur.com/rQURwew.jpg",
    "https://i.imgur.com/tqXr2r0.jpg",
    "https://i.imgur.com/hHDBlc4.jpg",
    "https://i.imgur.com/qVsroYZ.jpg",
    "https://i.imgur.com/M0Oozxg.jpg",
    "https://i.imgur.com/agcPy4L.jpg",
    "https://i.imgur.com/faxMwMo.jpg",
    "https://i.imgur.com/it5bTJH.jpg",
    "https://i.imgur.com/RoLTvaY.jpg",
    "https://i.imgur.com/fHUmYKZ.jpg",
    "https://i.imgur.com/kASEii5.jpg",
    "https://i.imgur.com/ogENZP6.jpg",
    "https://i.imgur.com/kRLqLiW.jpg",
    "https://i.imgur.com/R3GgGvs.jpg",
    "https://i.imgur.com/eOTZj0m.jpg",
    "https://i.imgur.com/OIpbivx.jpg",
    "https://i.imgur.com/53sbLcJ.jpg",
    "https://i.imgur.com/QG36cAF.jpg",
    "https://i.imgur.com/n7gLfl6.jpg",
    "https://i.imgur.com/lGGMZl7.jpg",
    "https://i.imgur.com/9m5ZkWO.jpg",
    "https://i.imgur.com/zOjnXzd.jpg",
    "https://i.imgur.com/qNuUWTk.jpg",
    "https://i.imgur.com/s8A0kfV.jpg",
    "https://i.imgur.com/JPwFZsH.jpg",
    "https://i.imgur.com/Ue7DhQ2.jpg",
    "https://i.imgur.com/J1hqo3F.jpg",
    "https://i.imgur.com/M6PeCOD.jpg",
    "https://i.imgur.com/rOOCNhH.jpg",
    "https://i.imgur.com/C9hFf8u.jpg",
    "https://i.imgur.com/y17x1Is.jpg",
    "https://i.imgur.com/xzerFhz.jpg",
    "https://i.imgur.com/3CRJ1e6.jpg",
    "https://i.imgur.com/ajrtZYc.jpg",
    "https://i.imgur.com/d5LitA3.jpg",
    "https://i.imgur.com/UfE1z05.jpg",
    "https://i.imgur.com/B7NR9R6.jpg",
    "https://i.imgur.com/UcPpqQN.jpg",
    "https://i.imgur.com/N3bcyPn.jpg",
    "https://i.imgur.com/XjVRQT8.jpg",
    "https://i.imgur.com/1ZSmZjr.jpg",
    "https://i.imgur.com/IoOeLEy.jpg",
    "https://i.imgur.com/Fa2ksE7.jpg",
    "https://i.imgur.com/eB2BSxF.jpg",
    "https://i.imgur.com/xilJteo.jpg",
    "https://i.imgur.com/kgXcZFs.jpg",
    "https://i.imgur.com/8tdTc6e.jpg",
    "https://i.imgur.com/wdJdpU3.jpg",
    "https://i.imgur.com/A48wuHU.jpg",
    "https://i.imgur.com/1ceSZFg.jpg",
    "https://i.imgur.com/pEvICGS.jpg",
    "https://i.imgur.com/RgzWthy.jpg",
    "https://i.imgur.com/H2L3SEj.jpg",
    "https://i.imgur.com/VULHTWA.jpg",
    "https://i.imgur.com/App2fiK.jpg",
    "https://i.imgur.com/yV1Xkk5.jpg",
    "https://i.imgur.com/RLD5hh3.jpg",
    "https://i.imgur.com/nDhYN3y.jpg",
    "https://i.imgur.com/Du5kQxH.jpg",
    "https://i.imgur.com/W56SRWF.jpg",
    "https://i.imgur.com/2behFVb.jpg",
    "https://i.imgur.com/PSBLlFK.jpg",
    "https://i.imgur.com/KuAlPAg.jpg",
    "https://i.imgur.com/7DNHFBv.jpg",
    "https://i.imgur.com/B2PrPwN.jpg",
    "https://i.imgur.com/BZ5uOY4.jpg",
    "https://i.imgur.com/KceO4v9.jpg",
    "https://i.imgur.com/7M31Bic.jpg",
    "https://i.imgur.com/KUMrVlJ.jpg",
    "https://i.imgur.com/fduIlMp.jpg",
    "https://i.imgur.com/9OCADui.jpg",
    "https://i.imgur.com/QvCxI1O.jpg",
    "https://i.imgur.com/aIKRKQF.jpg",
    "https://i.imgur.com/ZYRNLdO.jpg",
    "https://i.imgur.com/kxsjGY6.jpg",
    "https://i.imgur.com/GLFKqUp.jpg",
    "https://i.imgur.com/39mc3ti.jpg",
    "https://i.imgur.com/5kOoV7f.jpg",
    "https://i.imgur.com/g21oP0b.jpg",
    "https://i.imgur.com/ygTr3NR.jpg",
    "https://i.imgur.com/xcMz3pt.jpg",
    "https://i.imgur.com/6Uuciio.jpg",
    "https://i.imgur.com/KjxzYLT.jpg",
    "https://i.imgur.com/cl9wxjM.jpg",
    "https://i.imgur.com/cN3Q8CY.jpg",
    "https://i.imgur.com/syz2xR3.jpg",
    "https://i.imgur.com/VPc8GF5.jpg",
    "https://i.imgur.com/BX89ndh.jpg",
    "https://i.imgur.com/swHKW0G.jpg",
    "https://i.imgur.com/2Ml55lz.jpg",
    "https://i.imgur.com/74U5S0s.jpg",
    "https://i.imgur.com/OGJbkWp.jpg",
    "https://i.imgur.com/O7As5ur.jpg",
    "https://i.imgur.com/g4Nho3v.jpg",
    "https://i.imgur.com/Wf9vdTJ.jpg",
    "https://i.imgur.com/UYbIg1a.jpg",
    "https://i.imgur.com/Rt4roWc.jpg",
    "https://i.imgur.com/dKQiNzz.jpg",
    "https://i.imgur.com/CWwChIJ.jpg",
    "https://i.imgur.com/SoBjVP3.jpg",
    "https://i.imgur.com/jn9CukP.jpg",
    "https://i.imgur.com/yepVnJH.jpg",
    "https://i.imgur.com/Yyawlwy.jpg",
    "https://i.imgur.com/EFbQ4Wk.jpg",
    "https://i.imgur.com/Xn8umj9.jpg",
    "https://i.imgur.com/WId2ZwA.jpg",
    "https://i.imgur.com/lQcIbEZ.jpg",
    "https://i.imgur.com/yvPuVEz.jpg",
    "https://i.imgur.com/ELCcb1k.jpg",
    "https://i.imgur.com/IrYWn3v.jpg",
    "https://i.imgur.com/ULEfCjn.jpg",
    "https://i.imgur.com/u5L77DK.jpg",
    "https://i.imgur.com/0GoK47A.jpg",
    "https://i.imgur.com/wxgzfRK.jpg",
    "https://i.imgur.com/yLfydvD.jpg",
    "https://i.imgur.com/jd5vlfL.jpg",
    "https://i.imgur.com/A5UGDsl.jpg",
    "https://i.imgur.com/so79Wd2.jpg",
    "https://i.imgur.com/SwWpqj1.jpg",
    "https://i.imgur.com/jixHblI.jpg",
    "https://i.imgur.com/bDA64f9.jpg",
    "https://i.imgur.com/9fMjTFA.jpg",
    "https://i.imgur.com/exbcIju.jpg",
    "https://i.imgur.com/WF7dO4y.jpg",
    "https://i.imgur.com/90DIPPW.jpg",
    "https://i.imgur.com/LTwBXMc.jpg",
    "https://i.imgur.com/yp1Hdy0.jpg",
    "https://i.imgur.com/1KXcWvg.jpg",
    "https://i.imgur.com/Lxn1G7E.jpg",
    "https://i.imgur.com/1Oufotw.jpg",
    "https://i.imgur.com/cWIIP4l.jpg",
    "https://i.imgur.com/sfTEkH1.jpg",
    "https://i.imgur.com/xKGXCZm.jpg",
    "https://i.imgur.com/DMIT4OT.jpg",
    "https://i.imgur.com/jQc9BgQ.jpg",
    "https://i.imgur.com/WUZLLNm.jpg",
    "https://i.imgur.com/z3huATa.jpg",
    "https://i.imgur.com/zQTYfW8.jpg",
    "https://i.imgur.com/tg9vpG7.jpg",
    "https://i.imgur.com/zsSUEcx.jpg",
    "https://i.imgur.com/ORgsV4x.jpg",
    "https://i.imgur.com/CBwfyeK.jpg",
    "https://i.imgur.com/PQBK7ph.jpg",
    "https://i.imgur.com/hZMglUQ.jpg",
    "https://i.imgur.com/RZXC6qH.jpg",
    "https://i.imgur.com/gF27CRJ.jpg",
    "https://i.imgur.com/HFDkJOr.jpg",
    "https://i.imgur.com/inAjcPj.jpg",
    "https://i.imgur.com/OsZvLaX.jpg",
    "https://i.imgur.com/rYZaOLP.jpg",
    "https://i.imgur.com/P9u6P6y.jpg",
    "https://i.imgur.com/XOtlIiJ.jpg",
    "https://i.imgur.com/4bimtd9.jpg",
    "https://i.imgur.com/uqfs8fV.jpg",
    "https://i.imgur.com/sYuwVCB.jpg",
    "https://i.imgur.com/wWHTC1Z.jpg",
    "https://i.imgur.com/dhbtKx0.jpg",
    "https://i.imgur.com/o8y8nMN.jpg",
    "https://i.imgur.com/q7xaN5K.jpg",
    "https://i.imgur.com/Ec78qA9.jpg",
    "https://i.imgur.com/eFfxtKB.jpg",
    "https://i.imgur.com/5HaLSYT.jpg",
    "https://i.imgur.com/GLBj0SB.jpg",
    "https://i.imgur.com/SV9hZUN.jpg",
    "https://i.imgur.com/O7fB5Ud.jpg",
    "https://i.imgur.com/KRnfpLL.jpg",
    "https://i.imgur.com/FAQe6MB.jpg",
    "https://i.imgur.com/3dKMNOL.jpg",
    "https://i.imgur.com/8BDa8gm.jpg",
    "https://i.imgur.com/p6PyizO.jpg",
    "https://i.imgur.com/WdqEUtu.jpg",
    "https://i.imgur.com/SDXlA9P.jpg",
    "https://i.imgur.com/c2SToZx.jpg",
    "https://i.imgur.com/ulKh1Ij.jpg",
    "https://i.imgur.com/EYixe6a.jpg",
    "https://i.imgur.com/fXNLEHt.jpg",
    "https://i.imgur.com/TI0cGvA.jpg",
    "https://i.imgur.com/3HfrVRm.jpg",
    "https://i.imgur.com/VU66lcB.jpg",
    "https://i.imgur.com/slYI2ah.jpg",
    "https://i.imgur.com/X0qncMA.jpg",
    "https://i.imgur.com/yR7EYwz.jpg",
    "https://i.imgur.com/E5nff1J.jpg",
    "https://i.imgur.com/uM0F76o.jpg",
    "https://i.imgur.com/RnJz7pl.jpg",
    "https://i.imgur.com/9dhGc8a.jpg",
    "https://i.imgur.com/XxFySaF.jpg",
    "https://i.imgur.com/pJ3deOF.jpg",
    "https://i.imgur.com/etopsSw.jpg",
    "https://i.imgur.com/j2EdWFa.jpg",
    "https://i.imgur.com/HUMxA2j.jpg",
    "https://i.imgur.com/gDhDRwn.jpg",
    "https://i.imgur.com/To1xnRO.jpg",
    "https://i.imgur.com/R4afTMZ.jpg",
    "https://i.imgur.com/S1N3lCX.jpg",
    "https://i.imgur.com/L51TF0U.jpg",
    "https://i.imgur.com/7E5Cg5z.jpg",
    "https://i.imgur.com/2yS9jUO.jpg",
    "https://i.imgur.com/vyyr1lE.jpg",
    "https://i.imgur.com/34bGVVd.jpg",
    "https://i.imgur.com/j76x922.jpg",
    "https://i.imgur.com/B27SwLF.jpg",
    "https://i.imgur.com/u0wITEc.jpg",
    "https://i.imgur.com/vCQsYBr.jpg",
    "https://i.imgur.com/OzBSmYQ.jpg",
    "https://i.imgur.com/1PAX1VG.jpg",
    "https://i.imgur.com/mYUploK.jpg",
    "https://i.imgur.com/hkmthpt.jpg",
    "https://i.imgur.com/Dn7c7SB.jpg",
    "https://i.imgur.com/vjPhlZM.jpg",
    "https://i.imgur.com/KmkgM7D.jpg",
    "https://i.imgur.com/7LF8Tji.jpg",
    "https://i.imgur.com/2o07af6.jpg",
    "https://i.imgur.com/witWdoH.jpg",
    "https://i.imgur.com/RTEeePR.jpg",
    "https://i.imgur.com/dKwPGPn.jpg",
    "https://i.imgur.com/EtY3Ggr.jpg",
    "https://i.imgur.com/Ms5ABtO.jpg",
    "https://i.imgur.com/hd0OhjY.jpg",
    "https://i.imgur.com/nNp5jU3.jpg",
    "https://i.imgur.com/1sunuX1.jpg",
    "https://i.imgur.com/G9MPtxU.jpg",
    "https://i.imgur.com/HyfuheQ.jpg",
    "https://i.imgur.com/vtxfYEv.jpg",
    "https://i.imgur.com/sc8bnE1.jpg",
    "https://i.imgur.com/rtOvlob.jpg",
    "https://i.imgur.com/glbriTa.jpg",
    "https://i.imgur.com/rLGJ6LJ.jpg",
    "https://i.imgur.com/tuTCD4Q.jpg",
    "https://i.imgur.com/C6CEws8.jpg",
    "https://i.imgur.com/OVA2nqi.jpg",
    "https://i.imgur.com/xhY9lLr.jpg",
    "https://i.imgur.com/vWE2TZS.jpg",
    "https://i.imgur.com/PXrzrQP.jpg",
    "https://i.imgur.com/R9ZE6yg.jpg",
    "https://i.imgur.com/7KTNK6M.jpg",
    "https://i.imgur.com/VZgt6Tr.jpg",
    "https://i.imgur.com/wXzAUc6.jpg",
    "https://i.imgur.com/TXlFNtd.jpg",
    "https://i.imgur.com/iJgeJJ8.jpg",
    "https://i.imgur.com/WIYM86z.jpg",
    "https://i.imgur.com/x0aHzWm.jpg",
    "https://i.imgur.com/KOvt432.jpg",
    "https://i.imgur.com/mKXwmxX.jpg",
    "https://i.imgur.com/UXyqxkv.jpg",
    "https://i.imgur.com/3T2itBp.jpg",
    "https://i.imgur.com/qfjrDQt.jpg",
    "https://i.imgur.com/fGmnS3o.jpg",
    "https://i.imgur.com/keOJQwG.jpg",
    "https://i.imgur.com/uZgkh4Y.jpg",
    "https://i.imgur.com/yE1ktrW.jpg",
    "https://i.imgur.com/nByhuqU.jpg",
    "https://i.imgur.com/o4znmF2.jpg",
    "https://i.imgur.com/pFYhW1i.jpg",
    "https://i.imgur.com/NGcgFtk.jpg",
    "https://i.imgur.com/tnvq55Q.jpg",
    "https://i.imgur.com/4hvmeya.jpg",
    "https://i.imgur.com/WMugYbK.jpg",
    "https://i.imgur.com/H1NjRIx.jpg",
    "https://i.imgur.com/9CDqMa2.jpg",
    "https://i.imgur.com/krZTB4q.jpg",
    "https://i.imgur.com/YkzculB.jpg",
    "https://i.imgur.com/ciFZTDM.jpg",
    "https://i.imgur.com/bVpuPiz.jpg",
    "https://i.imgur.com/fhfawjm.jpg",
    "https://i.imgur.com/MWXBfny.jpg",
    "https://i.imgur.com/FZYzxmj.jpg",
    "https://i.imgur.com/2mN3fKG.jpg",
    "https://i.imgur.com/b9RWm2u.jpg",
    "https://i.imgur.com/lfWQzMP.jpg",
    "https://i.imgur.com/4Chh1yI.jpg",
    "https://i.imgur.com/Gh5kXrm.jpg",
    "https://i.imgur.com/DvYBjfk.jpg",
    "https://i.imgur.com/LuVqxkh.jpg",
    "https://i.imgur.com/upTNb7A.jpg",
    "https://i.imgur.com/xyU1OnA.jpg",
    "https://i.imgur.com/TKr6mo5.jpg",
    "https://i.imgur.com/cvLpwa2.jpg",
    "https://i.imgur.com/1Q7Nvls.jpg",
    "https://i.imgur.com/ku1HcDI.jpg",
    "https://i.imgur.com/oWV0KS0.jpg",
    "https://i.imgur.com/cW5kXMI.jpg",
    "https://i.imgur.com/1kMh0NN.jpg",
    "https://i.imgur.com/PViIvPa.jpg",
    "https://i.imgur.com/gj99yWY.jpg",
    "https://i.imgur.com/kwRUDb1.jpg",
    "https://i.imgur.com/AxSfhjl.jpg",
    "https://i.imgur.com/jNSpaDH.jpg",
    "https://i.imgur.com/C5eY60l.jpg",
    "https://i.imgur.com/FrHSdjm.jpg",
    "https://i.imgur.com/KgPaogI.jpg",
    "https://i.imgur.com/HjZLEo3.jpg",
    "https://i.imgur.com/2fw6uSh.jpg",
    "https://i.imgur.com/cGIgMg0.jpg",
    "https://i.imgur.com/nsKAAK3.jpg",
    "https://i.imgur.com/FZmbEnc.jpg",
    "https://i.imgur.com/Wm2wLzh.jpg",
    "https://i.imgur.com/SR2relm.jpg",
    "https://i.imgur.com/ki1ge56.jpg",
    "https://i.imgur.com/lBrsHfq.jpg",
    "https://i.imgur.com/AEHWWa5.jpg",
    "https://i.imgur.com/otXsyCU.jpg",
    "https://i.imgur.com/8ZaTC0d.jpg",
    "https://i.imgur.com/VXztyIl.jpg",
    "https://i.imgur.com/4yluvnW.jpg",
    "https://i.imgur.com/5YIBh1l.jpg",
    "https://i.imgur.com/yuq3Xvn.jpg",
    "https://i.imgur.com/l9pPecX.jpg",
    "https://i.imgur.com/Ba4jVyi.jpg",
    "https://i.imgur.com/OpZ5CQJ.jpg",
    "https://i.imgur.com/mkSiuo8.jpg",
    "https://i.imgur.com/sV9hyv1.jpg",
    "https://i.imgur.com/VdnLbKH.jpg",
    "https://i.imgur.com/daRR3AW.jpg",
    "https://i.imgur.com/dkr9MiC.jpg",
    "https://i.imgur.com/2fx7mIz.jpg",
    "https://i.imgur.com/Jov7bkY.jpg",
    "https://i.imgur.com/NMVqz7R.jpg",
    "https://i.imgur.com/WhNzaq1.jpg",
    "https://i.imgur.com/hmkw1lq.jpg",
    "https://i.imgur.com/NUyv8vF.jpg",
    "https://i.imgur.com/5uknmoz.jpg",
    "https://i.imgur.com/9yCS0xP.jpg",
    "https://i.imgur.com/FBsKiKH.jpg",
    "https://i.imgur.com/vrJ8nuZ.jpg",
    "https://i.imgur.com/O6i88H5.jpg",
    "https://i.imgur.com/hab1lHH.jpg",
    "https://i.imgur.com/EBehh7S.jpg",
    "https://i.imgur.com/jsoBea1.jpg",
    "https://i.imgur.com/Jwiuhjq.jpg",
    "https://i.imgur.com/2VhNsr4.jpg",
    "https://i.imgur.com/sy3oqFw.jpg",
    "https://i.imgur.com/Xr2m18J.jpg",
    "https://i.imgur.com/4rMSCLN.jpg",
    "https://i.imgur.com/DuPAtgy.jpg",
    "https://i.imgur.com/nzmNEDM.jpg",
    "https://i.imgur.com/OP5BYBO.jpg",
    "https://i.imgur.com/uvhgtst.jpg",
    "https://i.imgur.com/MoNd9D5.jpg",
    "https://i.imgur.com/Cjhcd3o.jpg",
    "https://i.imgur.com/riDcMEt.jpg",
    "https://i.imgur.com/BTisUpi.jpg",
    "https://i.imgur.com/8CvNUI2.jpg",
    "https://i.imgur.com/gP6Z624.jpg",
    "https://i.imgur.com/bqL2PNw.jpg",
    "https://i.imgur.com/IiU9RbG.jpg",
    "https://i.imgur.com/HpzsvBX.jpg",
    "https://i.imgur.com/Ib3WQID.jpg",
    "https://i.imgur.com/qgVgLUs.jpg",
    "https://i.imgur.com/aP3EBF9.jpg",
    "https://i.imgur.com/bI0YMK3.jpg",
    "https://i.imgur.com/UEgOLZB.jpg",
    "https://i.imgur.com/dahZ3cO.jpg",
    "https://i.imgur.com/LD4djDY.jpg",
    "https://i.imgur.com/T7hhDav.jpg",
    "https://i.imgur.com/NWaaGtL.jpg",
    "https://i.imgur.com/qg0Q7Dp.jpg",
    "https://i.imgur.com/owNRlAF.jpg",
    "https://i.imgur.com/Bt8lzZR.jpg",
    "https://i.imgur.com/zzlEIzY.jpg",
    "https://i.imgur.com/pcYYSAI.jpg",
    "https://i.imgur.com/JOCTDVr.jpg",
    "https://i.imgur.com/XNriRHd.jpg",
    "https://i.imgur.com/BgVBghd.jpg",
    "https://i.imgur.com/ZiErx0G.jpg",
    "https://i.imgur.com/QFNGmQk.jpg",
    "https://i.imgur.com/YqSuHdN.jpg",
    "https://i.imgur.com/7M623VL.jpg",
    "https://i.imgur.com/RfoN3aw.jpg",
    "https://i.imgur.com/9YKhg13.jpg",
    "https://i.imgur.com/kIBjl5o.jpg",
    "https://i.imgur.com/QxKqyvj.jpg",
    "https://i.imgur.com/nhVCZv8.jpg",
    "https://i.imgur.com/u1mlo7s.jpg",
    "https://i.imgur.com/5ya1PUh.jpg",
    "https://i.imgur.com/NDAGMHE.jpg",
    "https://i.imgur.com/fFZFj73.jpg",
    "https://i.imgur.com/p3Ov2y8.jpg",
    "https://i.imgur.com/tAU23sB.jpg",
    "https://i.imgur.com/J9pjpla.jpg",
    "https://i.imgur.com/Kony5OF.jpg",
    "https://i.imgur.com/XSYzdb8.jpg",
    "https://i.imgur.com/2pX6VCQ.jpg",
    "https://i.imgur.com/turIoBr.jpg",
    "https://i.imgur.com/axiRnhV.jpg",
    "https://i.imgur.com/LCKnLsK.jpg",
    "https://i.imgur.com/NN5XUpl.jpg",
    "https://i.imgur.com/imoh9WV.jpg",
    "https://i.imgur.com/sGvDmRu.jpg",
    "https://i.imgur.com/OVhwysb.jpg",
    "https://i.imgur.com/DnIPFUL.jpg",
    "https://i.imgur.com/7BGhLKm.jpg",
    "https://i.imgur.com/UcdjL61.jpg",
    "https://i.imgur.com/sra4MGp.jpg",
    "https://i.imgur.com/QDJ70ZV.jpg",
    "https://i.imgur.com/lydUzk7.jpg",
    "https://i.imgur.com/hTA16Nj.jpg",
    "https://i.imgur.com/05AaY5y.jpg",
    "https://i.imgur.com/IR643C6.jpg",
    "https://i.imgur.com/kYFhOq3.jpg",
    "https://i.imgur.com/X3e5mGH.jpg",
    "https://i.imgur.com/f0NrF6N.jpg",
    "https://i.imgur.com/FAxeCOn.jpg",
    "https://i.imgur.com/afohAQH.jpg",
    "https://i.imgur.com/5yHpB5O.jpg",
    "https://i.imgur.com/doeJZ6j.jpg",
    "https://i.imgur.com/pZMqoh6.jpg",
    "https://i.imgur.com/GIyayUq.jpg",
    "https://i.imgur.com/qwukSbh.jpg",
    "https://i.imgur.com/M0GGn5B.jpg",
    "https://i.imgur.com/M5SWMX7.jpg",
    "https://i.imgur.com/Qi49PRM.jpg",
    "https://i.imgur.com/mGvjPJc.jpg",
    "https://i.imgur.com/YWlvok3.jpg",
    "https://i.imgur.com/tFzddem.jpg",
    "https://i.imgur.com/Jom2olq.jpg",
    "https://i.imgur.com/NwzNBa2.jpg",
    "https://i.imgur.com/cnwrW7G.jpg",
    "https://i.imgur.com/Hes74cC.jpg",
    "https://i.imgur.com/xAXw23v.jpg",
    "https://i.imgur.com/7C68cL8.jpg",
    "https://i.imgur.com/VO6OHlk.jpg",
    "https://i.imgur.com/EGvHYPJ.jpg",
    "https://i.imgur.com/Edwo6NO.jpg",
    "https://i.imgur.com/HrvGOkT.jpg",
    "https://i.imgur.com/redeX9D.jpg",
    "https://i.imgur.com/AO6n1Cv.jpg",
    "https://i.imgur.com/jXcJ37f.jpg",
    "https://i.imgur.com/iLZVnyj.jpg",
    "https://i.imgur.com/E9R4McI.jpg",
    "https://i.imgur.com/DJxMQCa.jpg",
    "https://i.imgur.com/AUpCn0i.jpg",
    "https://i.imgur.com/idN3Q3m.jpg",
    "https://i.imgur.com/qpHQpFY.jpg",
    "https://i.imgur.com/Ul2QkD6.jpg",
    "https://i.imgur.com/UIIPtWr.jpg",
    "https://i.imgur.com/y0dGNh6.jpg",
    "https://i.imgur.com/ORoLUdE.jpg",
    "https://i.imgur.com/SnXYeMK.jpg",
    "https://i.imgur.com/vrf0XQk.jpg",
    "https://i.imgur.com/Qlx7KJ4.jpg",
    "https://i.imgur.com/mgTAyXP.jpg",
    "https://i.imgur.com/sAOKuig.jpg",
    "https://i.imgur.com/mgCD5gY.jpg",
    "https://i.imgur.com/SaDlvpW.jpg",
    "https://i.imgur.com/asmHMBD.jpg",
    "https://i.imgur.com/dixibOZ.jpg",
    "https://i.imgur.com/aanBen7.jpg",
    "https://i.imgur.com/FSpFirb.jpg",
    "https://i.imgur.com/VtMeI5z.jpg",
    "https://i.imgur.com/bpx838L.jpg",
    "https://i.imgur.com/INGdjCG.jpg",
    "https://i.imgur.com/TK0GS8W.jpg",
    "https://i.imgur.com/gMgWyzw.jpg",
    "https://i.imgur.com/3Kqs51J.jpg",
    "https://i.imgur.com/fu5oFBZ.jpg",
    "https://i.imgur.com/2rg5ez2.jpg",
    "https://i.imgur.com/EtkEjiD.jpg",
    "https://i.imgur.com/4vNPsWl.jpg",
    "https://i.imgur.com/s2QLvfd.jpg",
    "https://i.imgur.com/SjVxNFa.jpg",
    "https://i.imgur.com/G7XIssl.jpg",
    "https://i.imgur.com/Oxddr6e.jpg",
    "https://i.imgur.com/6eCoGlx.jpg",
    "https://i.imgur.com/n4ITtYl.jpg",
    "https://i.imgur.com/bQJiex9.jpg",
    "https://i.imgur.com/tSEZyZe.jpg",
    "https://i.imgur.com/srqJDIN.jpg",
    "https://i.imgur.com/oZSi01T.jpg",
    "https://i.imgur.com/BY7J3a9.jpg",
    "https://i.imgur.com/pC8v9Ho.jpg",
    "https://i.imgur.com/e8pPmPv.jpg",
    "https://i.imgur.com/FZNZrmg.jpg",
    "https://i.imgur.com/8qk4gq0.jpg",
    "https://i.imgur.com/0dM5C3z.jpg",
    "https://i.imgur.com/BpPqoff.jpg",
    "https://i.imgur.com/Q2pMP3i.jpg",
    "https://i.imgur.com/p3LodXX.jpg",
    "https://i.imgur.com/vCKIb0O.jpg",
    "https://i.imgur.com/JkIl50k.jpg",
    "https://i.imgur.com/T20aoHN.jpg",
    "https://i.imgur.com/3UGXnIo.jpg",
    "https://i.imgur.com/gryzOen.jpg",
    "https://i.imgur.com/NP0sdUc.jpg",
    "https://i.imgur.com/q0rKNsr.jpg",
    "https://i.imgur.com/0CQobFI.jpg",
    "https://i.imgur.com/X24SK2G.jpg",
    "https://i.imgur.com/eSAueQz.jpg",
    "https://i.imgur.com/oRVOR0W.jpg",
    "https://i.imgur.com/EkHWUpa.jpg",
    "https://i.imgur.com/5bIODpC.jpg",
    "https://i.imgur.com/vm0Sq3F.jpg",
    "https://i.imgur.com/qKVZs8U.jpg",
    "https://i.imgur.com/v3Zyyob.jpg",
    "https://i.imgur.com/hNbsZ43.jpg",
    "https://i.imgur.com/kVQx8Za.jpg",
    "https://i.imgur.com/KO6rtui.jpg",
    "https://i.imgur.com/EHSF0cM.jpg",
    "https://i.imgur.com/SkouUM6.jpg",
    "https://i.imgur.com/gnIHYP4.jpg",
    "https://i.imgur.com/NJPvfEg.jpg",
    "https://i.imgur.com/Q0NiO3V.jpg",
    "https://i.imgur.com/Js4PDKC.jpg",
    "https://i.imgur.com/KJuO7fI.jpg",
    "https://i.imgur.com/jdoPS0o.jpg",
    "https://i.imgur.com/IWm8yiW.jpg",
    "https://i.imgur.com/6pchJmm.jpg",
    "https://i.imgur.com/ptmUUKZ.jpg",
    "https://i.imgur.com/5hWZts5.jpg",
    "https://i.imgur.com/2cNXMs8.jpg",
    "https://i.imgur.com/aCa5OMy.jpg",
    "https://i.imgur.com/bkAhQ9N.jpg",
    "https://i.imgur.com/qNCbsbB.jpg",
    "https://i.imgur.com/GtsceRX.jpg",
    "https://i.imgur.com/knpwcJz.jpg",
    "https://i.imgur.com/4tYwzr1.jpg",
    "https://i.imgur.com/1oy8l4D.jpg",
    "https://i.imgur.com/l1VPp1w.jpg",
    "https://i.imgur.com/JiWVLKb.jpg",
    "https://i.imgur.com/DoCnERH.jpg",
    "https://i.imgur.com/HlbIwkQ.jpg",
    "https://i.imgur.com/MfMSEU2.jpg",
    "https://i.imgur.com/3nKvsP4.jpg",
    "https://i.imgur.com/IfeE7Sv.jpg",
    "https://i.imgur.com/UVc7zzE.jpg",
    "https://i.imgur.com/PijhNE3.jpg",
    "https://i.imgur.com/xAbHS9o.jpg",
    "https://i.imgur.com/JFA1uj3.jpg",
    "https://i.imgur.com/eWDRrWW.jpg",
    "https://i.imgur.com/pJSbboG.jpg",
    "https://i.imgur.com/puvzf9A.jpg",
    "https://i.imgur.com/kW0eOV7.jpg",
    "https://i.imgur.com/BFvIw8e.jpg",
    "https://i.imgur.com/a9mB7u1.jpg",
    "https://i.imgur.com/0wWCX3A.jpg",
    "https://i.imgur.com/wmuIp2v.jpg",
    "https://i.imgur.com/HsAErrS.jpg",
    "https://i.imgur.com/WbF0OlG.jpg",
    "https://i.imgur.com/gwFrHEI.jpg",
    "https://i.imgur.com/otFFsWa.jpg",
    "https://i.imgur.com/Y5kMtPx.jpg",
    "https://i.imgur.com/SYZG96w.jpg",
    "https://i.imgur.com/UyZTIsY.jpg",
    "https://i.imgur.com/ElhzeLV.jpg",
    "https://i.imgur.com/oqmN63X.jpg",
    "https://i.imgur.com/MOdMOK0.jpg",
    "https://i.imgur.com/FvfHdOA.jpg",
    "https://i.imgur.com/cZlLEEu.jpg",
    "https://i.imgur.com/D2sPVkC.jpg",
    "https://i.imgur.com/EW5q1ev.jpg",
    "https://i.imgur.com/NpcjNSI.jpg",
    "https://i.imgur.com/Mg0TQMj.jpg",
    "https://i.imgur.com/8zLYYH8.jpg",
    "https://i.imgur.com/eaZphrq.jpg",
    "https://i.imgur.com/VONcWnd.jpg",
    "https://i.imgur.com/68kFPrv.jpg",
    "https://i.imgur.com/yScLAks.jpg",
    "https://i.imgur.com/nvajuGw.jpg",
    "https://i.imgur.com/alhoCgY.jpg",
    "https://i.imgur.com/Gh2B3Ci.jpg",
    "https://i.imgur.com/2pTtDYr.jpg",
    "https://i.imgur.com/0DgQDr5.jpg",
    "https://i.imgur.com/X6wJ8or.jpg",
    "https://i.imgur.com/ykTjYGY.jpg",
    "https://i.imgur.com/R8lpHMy.jpg",
    "https://i.imgur.com/an66qyi.jpg",
    "https://i.imgur.com/SBGzTjM.jpg",
    "https://i.imgur.com/EkBBy7K.jpg",
    "https://i.imgur.com/8FbsU47.jpg",
    "https://i.imgur.com/cndjyDY.jpg",
    "https://i.imgur.com/S0U3m6h.jpg",
    "https://i.imgur.com/BoskkkC.jpg",
    "https://i.imgur.com/Ifq18ht.jpg",
    "https://i.imgur.com/E7LYwBD.jpg",
    "https://i.imgur.com/KjqZVbf.jpg",
    "https://i.imgur.com/NH8FfQy.jpg",
    "https://i.imgur.com/aIF456r.jpg",
    "https://i.imgur.com/mhJ7dR1.jpg",
    "https://i.imgur.com/TqLklKz.jpg",
    "https://i.imgur.com/ygHPeh1.jpg",
    "https://i.imgur.com/O1kHc3o.jpg",
    // Thêm các URL hình ảnh khác nếu cần thiết
  ];
  // Mảng chứa các chuỗi ngẫu nhiên bạn muốn thay thế
  const randomStrings = [
    "Bầu trời xanh, làn mây trắng. Anh yêu nắng hay yêu em?.",
  
    "Nhờ có nắng mới thấy cầu vồng. Nhờ có anh mới thấy màu hạnh phúc.",
  
    "Anh yêu ơi ới ời. Anh đang ở đâu?.",
  
    "Soái ca là của ngôn tình. Còn anh thì chỉ của mình em thôi.",
  
    "Giữa cuộc đời hàng ngàn cám dỗ.Em chỉ cần bến đỗ anh thôi.",
  
    "Bồ công anh bay khi có gió. Em chỉ cười vì ở đó có anh.",
  
    "Chỉ cần anh nói yêu, em sẽ bám theo anh suốt đời. Cô gái đang muốn muốn bật đèn xanh đấy. Cô nàng muốn gợi ý là mình chung thủy lắm đấy. Anh cứ thử tỏ tình mà xem.",
  
    "Ba mươi chưa phải là Tết. Không làm bạn đâu phải là hết, còn có thể làm người yêu mà.",
  
    "Ai nào cho mượn avatar để em đỡ cô đơn đi.",
  
    "Nắng đã có mũ, mưa đã có ô, còn em sẽ có ai?.",
  
    "Chồng tương lai ơi, em chờ anh hơi lâu rồi đấy.",
  
    "Trời đổ mưa rồi sao anh chưa đổ em?.",
  
    "Dạo này anh có thấy mỏi chân? Sao cứ đi trong tim em mãi.",
  
    "Anh ơi, có nóng không? Tim em đang cháy nè.",
  
    "Anh gì ơi ! Anh đánh rơi người yêu này.",
  
    "Sao anh cười mãi thế. Da em đen mất rồi.",
  
    "Ủa đêm rồi mà sao tim mình vẫn đầy nắng thế?.",
  
    "Tim anh còn chỗ không? Em muốn chuyển nhà mà chưa tìm thấy chỗ.",
  
    "Uống nhầm 1 ánh mắt cơn say theo cả đời!.",
  
    "Em thích anh còn nhiều hơn muối ở biển…",
  
    "Em đọc hết “Mười vạn câu hỏi vì sao” những vẫn không hiểu được vì sao em thích anh nhiều thế.",
  
    "Đường thì dài, chân em thì ngắn. Phải đi bao xa mới có thể tìm thấy anh.",
  
    "Em xinh tươi, nhưng em chưa thuộc về ai.",
  
    "Chán thả thính rồi, ai cưa để em đổ một lần coi.",
  
    "Có phải cuộc sống quá bon chen nên anh mãi vẫn chưa tìm đến em?.",
  
    "Nếu có thể hãy để em một lần được yêu anh, được không?.",
  
    "Tuổi tác với chị không quan trọng, vấn đề là em đã có bằng lái chưa?.",
  
    "Trăng lên đỉnh núi trăng tà. Anh yêu em thật hay là yêu chơi?.",
  
    "Nếu ngoài kia nhiều bão tố, thì về đây với em.",
  
    "Em không muốn ngủ muộn, chỉ là đang chờ ai đó chúc ngủ ngon thôi.",
  
    "Cây đa, giếng nước sân đinh. Khi nào em hết một mình đây anh?.",
  
    "Cả thế giới này ai cũng yêu nhau chỉ có riêng mình em hẩm hiu một góc.",
  
    "Cần ai đó quan tâm để thấy mình được yêu thương.",
  
    "Anh gì ơi,cho em mượn đèn pin được không? Trời tối quá, em không tìm thấy đường vào tim anh.",
  
    "Say rượu say bia làm gì? Anh say em đi này.",
  
    "Thách ai nói yêu em đấy.",
  
    "Em ăn BƠ muốn vỡ bụng rồi đây ạ. Làng Face ai HẢO TÂM làm ơn cứu em với. Chỉ cần cái status này 500 like, bụng em lại lành!.",
  
    "Lâu rồi chưa biết cảm giác được đi ăn đi xem phim như thế nào, bài vở nhiều quá. Hôm nay rảnh có ai mời không nhỉ?.",
  
    "Rảnh quá có ai muốn đi chơi với mình không …",
  
    "Này anh, anh xem hộ em xem trong mắt em có gì hộ cái. Thấy chưa, toàn là hình bóng anh đấy!.",
  
    "Anh biết nhiều về Thuốc Mê không? Còn em gói gọn lại đó là anh.",
      "Trong tim em có chỗ nào cho anh không?.",
  
            "Vận tốc trái tim nhanh không em nhỉ? Để anh tính quãng đường đi đến trái tim em..",
  
            "Mây là của trời, em là của anh (tag tên chính chủ vào) Khẳng định chủ quyền rồi nhé. Nếu được tag tên mình vào thì từ nay cấm đi thả thính lung tung nhá.",
  
            "Ngoài kia đám cưới linh đình. Bao giờ thì đến lượt mình em ơi.",
  
            "Tay anh đây ấm lắm, em muốn nắm thử không?.",
  
            "1, 2, 3, 5 em có đánh rơi nhịp nào không?.",
  
            "Em xinh đẹp ơi, làm con dâu mẹ anh không?.",
  
            "Cần lắm một em gái mưa!.",
  
            "Giá có em người yêu để cùng khám phá thế giới.",
  
            "Mình cũng đẹp trai, sao chả ai để ý?.",
  
            "Đông về tay anh lạnh lắm, nhưng anh vẫn sẵn lòng sưởi ấm tay em.",
  
            "Mọi người đều yêu cái đẹp, nên anh yêu em.",
  
            "Bão to, cây đổ. Sao em chưa đổ anh?.",
  
            "Bố em có phải là một thợ kim hoàn không? Sao em giống viên kim cương vậy?.",
  
            "Với thế giới thì em chỉ là một người. Còn với anh, em là cả thế giới.",
  
            "Bố em có phải là tên trộm không? Sao có thể trộm vì sao và gắn vào mắt em như thế?.",
  
            "Anh như thế này, đã đủ tiêu chuẩn làm bạn trai em chưa?.",
  
            "Em có muốn làm Mặt Trời duy nhất của anh không?",
  
            "Này em ơi, mẹ anh đang gọi con dâu kìa.",
  
            "Giờ nếu có cô gái nào nguyện bên anh, anh sẽ khiến cô ấy hạnh phúc mãi về sau.",
  
            "Chỉ cần em yêu anh thôi, còn cả thế giới cứ để anh lo.",
  
            "Cuộc đời này chắc chắn không như ý anh muốn, vậy em sẽ như ý anh muốn.",
  
            "Em có thể đưa anh đến tiệm bánh được không? Vì anh cũng muốn có một chiếc bánh Cutie giống như em vậy.",
  
            "Cho anh hỏi em một chút được không?…. Anh trông em rất là quen….Anh nghĩ là? Mình có biết nhau không?(Chém với gái lạ thì chắc chắn sẽ bảo không rồi)….Thế à. Trông em rất giống người yêu tương lai của anh. ?.",
  
            "Anh là…. Còn em tên gì? (Em tên Quỳnh Anh) Quỳnh Anh Cái tên là là đẹp nhưng mà về sau anh sẽ không đặt tên con gái mình là Quỳnh Anh vì suốt ngày phải lên bảng.",
  
            "Anh muốn hỏi em một câu này,…thực ra đấy không phải là một câu hỏi. Anh chỉ muốn nói là… Nếu như mà em là CocaCola thì anh sẽ là Pepsi! (Nghĩa là chúng ta là một cặp đồ uống đẹp đôi).",
  
            "Chán thả thính rồi, ai cưa đi để anh đổ thử một lần.",
  
            "Anh cá với em rằng em là tay trộm chuyên nghiệp. Bởi vì anh mới nhìn thấy em ở đây và trong nháy mắt là em đã đánh cắp trái tim của anh rồi.",
  
            "Ngày đó trời mưa lớn lắm, anh gặp được em, em không thấy anh, anh không thấy mưa.",
  
            "Đố em một con gấu bắc cực nặng bao nhiêu kg? (Thường thì các cô gái sẽ trả lời không) Đáp: Anh cũng không biết nhưng anh biết con gấu bắc cực đủ nặng để phá vỡ tảng băng giữa chúng ta.",
  
            "Nếu mỗi lần nhớ tới em anh được 500 đồng chắc giờ này anh đã vượt xa Bill Gates.",
  
            "Em có biết rằng anh nhớ em nhiều lắm không? Anh ăn không ngon nhưng ngủ như điên, anh đi giầy quên đi tất, ăn sáng quên đánh răng, anh dùng xăng vo gạo, anh khờ khạo cũng chỉ vì yêu em đó.",
  
            "Em ơi! Em là nghề gì đấy….? Sao đêm nào em cũng hiện lên trong giấc mơ của anh vậy? Anh chẳng biết làm thế nào nữa cả. Làm người yêu anh em nhé!.",
  
            "Em ơi ! Khi em đọc tin nhắn này, em nợ anh cuộc hẹn. Xóa tin nhắn này, em nợ anh cuộc tình. Lưu tin là em nợ anh 1 nụ hôn. Trả lời anh, em nợ anh tất cả. Còn nếu em không trả lời thì em đã yêu anh !!! hihi.",
  
            "Ðiều duy nhất đôi mắt em chưa nói cho anh biết là tên của em.",
  
            "Anh thà được một lần ngửi được mùi tóc thơm của em. Anh thà được mộ lần xiết chặt bàn tay của em, anh thà được một lần nếm hương vị ngọt từ nụ hôn của em còn hơn là sống bất tử mà không được điều ấy.",
  
            "Chứng nghiện thức đêm cùng nỗi nhớ em, anh đã cố nhưng sửa không được.",
  
            "Anh muốn gửi tin nhắn này đến em hôm nay vì hôm nay anh cảm thấy yêu em nhiều đến bất thường.",
  
            " Anh ghét em lắm em biết không? Vì suốt ngày em cứ bay lượn trong đầu anh, làm anh khôn nghĩ được việc gì cả…huhu.",
  
            "Giá em mở hiệu cầm đồ\nHôm nào anh đến giả vờ cầm tay",
  
            "Muốn thấy cọp thì vào sở thú\nMuốn tìm chỗ trú thì vào tim anh.",
  
            "Thời tiết trái gió trở trời\nTrái tim lỡ nhịp cả đời thương em",
  
            "Em có thể cho anh mượn một nụ hôn được không? Anh hứa là sẽ trả lại đầy đủ.",
  
            "Mẹ mua cho con heo đất\nTiền anh đem cất, sau này cưới em",
  
            "Nhìn anh trông có đủ ngầu\nĐể em quên mối tình đầu hay chưa?",
  
            "Sáng nay ăn bát cháo lòng\nAnh ăn hết cháo, để lòng yêu em",
  
            "Em biết em và cái ly khác nhau ở điểm gì không?\nCái ly dễ vỡ, em thì dễ thương!",
  
            "Monday là thứ hai\nTuesday là thứ ba\nCòn bao giờ tôi mới được benemday?",
  
    "Trời xanh mây trắng nắng vàng\nAnh thơm vào má của nàng được không?",
  
    "Đen Vâu muốn trồng rau và nuôi thêm cá\nCòn anh lại muốn hỏi má để nuôi thêm em",
  
    "Đậu hủ phải có mắm tôm\nYêu anh sẽ được anh ôm mỗi ngày.",
  
    // Thêm các chuỗi ngẫu nhiên khác nếu cần thiết
  ];

  async function downloadImage(url) {
    try {
      const response = await axios({
        method: 'GET',
        url: url,
        responseType: 'stream' // Xác định kiểu dữ liệu trả về là stream
      });
      return response.data; // Trả về dữ liệu như một stream
    } catch (error) {
      console.error('Error downloading image:', error);
      return null;
    }
  }
  
  // Hàm lấy nhiều URL hình ảnh ngẫu nhiên
  async function getRandomImageStreams(count) {
    const randomImageStreams = [];
    for (let i = 0; i < count; i++) {
      const randomIndex = Math.floor(Math.random() * imageUrls.length);
      const imageUrl = imageUrls[randomIndex];
      const imageStream = await downloadImage(imageUrl);
      if (imageStream) {
        randomImageStreams.push(imageStream);
      }
    }
    return randomImageStreams;
  }
  
  module.exports.onLoad = o => {
    if (!!global.autosendmessage_setinterval) clearInterval(global.autosendmessage_setinterval);
    global.autosendmessage_setinterval = setInterval(async function() {
      if (á = config.find(i => i.timer == new Date(Date.now() + 25200000).toLocaleString().split(/,/).pop().trim())) {
        var msg = r(á.message);
        msg = msg.replace(/{time}/g, (require("moment-timezone")).tz("Asia/Ho_Chi_Minh").format("HH:mm:ss (D/MM/YYYY) (dddd)"));
        msg = msg.replace(/{thinh}/g, getRandomString()); // Thay thế "{thinh}" bằng chuỗi ngẫu nhiên
        const imageCount = Math.floor(Math.random() * 4) + 1; // Lấy ngẫu nhiên từ 1 đến 4 ảnh
        const imageStreams = await getRandomImageStreams(imageCount);
        msg = {
          body: msg,
          attachment: imageStreams // Truyền mảng các stream hình ảnh ngẫu nhiên
        };
        global.data.allThreadID.forEach(i => o.api.sendMessage(msg, i));
      };
    }, 1000);
  };
  
  // Hàm lấy chuỗi ngẫu nhiên từ mảng randomStrings
  function getRandomString() {
    const randomIndex = Math.floor(Math.random() * randomStrings.length);
    return randomStrings[randomIndex];
  }
  
  module.exports.run = () => {};
  